import type { TestCategory, TestDefinition } from '../types';
import {
  bodyField,
  BROWSER_HEADERS,
  headersField,
  linesField,
  methodField,
  numberField,
  pathField,
  queryField,
  SECTION,
} from './helpers';

/** API Protection — authentication, authorisation and business-logic abuse. */
export const apiTests: TestDefinition[] = [
  {
    id: 'brute_force',
    category: 'api_protection',
    label: 'Brute Force Test',
    shortLabel: 'Brute Force',
    icon: 'key',
    blurb: 'Replay a password dictionary against a login endpoint to test lockout and rate limiting.',
    feasibility: 'phone',
    feasibilityNote:
      'Low-volume credential testing is fully effective from a handset and is deliberately rate-limited to stay lockout-aware.',
    creditCost: 1,
    defaultDurationMs: 12000,
    http: {
      method: 'POST',
      path: '/api/auth/login',
      headers: [
        { key: 'Content-Type', value: 'application/json' },
        ...BROWSER_HEADERS,
        { key: 'X-Requested-With', value: 'XMLHttpRequest' },
      ],
      body: '{"username": "admin", "password": "{{PAYLOAD}}"}',
    },
    sections: [
      { id: SECTION.target, title: 'Primary Target' },
      { id: 'bf_http', title: 'Brute Force Parameters', accent: true },
      { id: 'request', title: '' },
      { id: 'bf_attack', title: 'Brute Force Attack Parameters' },
    ],
    fields: [
      methodField('bf_http', 'POST'),
      pathField('bf_http', '/api/auth/login'),
      headersField('request', [
        { key: 'Content-Type', value: 'application/json' },
        ...BROWSER_HEADERS,
        { key: 'X-Requested-With', value: 'XMLHttpRequest' },
      ]),
      bodyField('request', '{"username": "admin", "password": "{{PAYLOAD}}"}'),
      {
        id: 'bf.username',
        type: 'text',
        section: 'bf_attack',
        label: 'Target Username',
        default: 'admin',
        hint: 'Username to brute force',
      },
      linesField(
        'bf.passwords',
        'bf_attack',
        'Passwords (one per line)',
        ['password', '123456', 'admin'],
        'Password dictionary, one candidate per line',
      ),
      numberField('bf.delay', 'bf_attack', 'Request Delay (ms)', {
        min: 0,
        max: 10000,
        def: 100,
        hint: 'Delay between attempts to avoid detection (0-10000)',
      }),
      {
        id: 'bf.endpoint',
        type: 'text',
        section: 'bf_attack',
        label: 'API Endpoint',
        default: '/api/auth/login',
        hint: 'Authentication endpoint to attack',
        mono: true,
      },
      {
        id: 'bf.lockout_threshold',
        type: 'number',
        section: 'bf_attack',
        label: 'Lockout Threshold',
        min: 0,
        max: 100,
        default: 0,
        hint: 'Stop after this many consecutive rejections; 0 disables the guard (0-100)',
        advanced: true,
      },
    ],
  },
  {
    id: 'idor_enumeration',
    category: 'api_protection',
    label: 'IDOR Enumeration',
    shortLabel: 'IDOR Enumeration',
    icon: 'id-card',
    blurb: 'Enumerate object identifiers to find records reachable without proper authorisation.',
    feasibility: 'phone',
    feasibilityNote: 'Pure HTTP request/response work — fully effective from a handset.',
    creditCost: 1,
    defaultDurationMs: 10000,
    http: {
      method: 'GET',
      path: '/api/users',
      query: [
        { key: 'id', value: '{{PAYLOAD}}' },
        { key: 'format', value: 'json' },
      ],
      headers: [
        { key: 'Authorization', value: 'Bearer {{TOKEN}}' },
        ...BROWSER_HEADERS,
      ],
    },
    sections: [
      { id: SECTION.target, title: 'Primary Target' },
      { id: 'idor_http', title: 'IDOR Enumeration Parameters', accent: true },
      { id: 'request', title: '' },
      { id: 'idor_config', title: 'Enumeration / IDOR Config' },
    ],
    fields: [
      methodField('idor_http', 'GET'),
      pathField('idor_http', '/api/users'),
      queryField('request', [
        { key: 'id', value: '{{PAYLOAD}}' },
        { key: 'format', value: 'json' },
      ]),
      headersField('request', [
        { key: 'Authorization', value: 'Bearer {{TOKEN}}' },
        ...BROWSER_HEADERS,
      ]),
      numberField('idor.start', 'idor_config', 'Start ID', {
        min: 0,
        max: 1_000_000_000,
        def: 1,
        hint: 'First identifier in the enumeration range (0-1000000000)',
      }),
      numberField('idor.end', 'idor_config', 'End ID', {
        min: 0,
        max: 1_000_000_000,
        def: 10,
        hint: 'Last identifier in the enumeration range (0-1000000000)',
      }),
      numberField('idor.step', 'idor_config', 'Step', {
        min: 1,
        max: 1000,
        def: 1,
        hint: 'Increment between identifiers (1-1000)',
      }),
      {
        id: 'idor.baseline_id',
        type: 'number',
        section: 'idor_config',
        label: 'Baseline ID',
        min: 0,
        max: 1_000_000_000,
        default: 0,
        hint: 'A known-unauthorised identifier used as the 403/404 baseline for comparison',
        advanced: true,
      },
    ],
  },
  {
    id: 'schema_validation',
    category: 'api_protection',
    label: 'Schema Validation Test',
    shortLabel: 'Schema Validation',
    icon: 'code-working',
    blurb: 'Fuzz malformed bodies across content types to find missing input-schema enforcement.',
    feasibility: 'phone',
    feasibilityNote: 'Pure HTTP request/response work — fully effective from a handset.',
    creditCost: 1,
    defaultDurationMs: 10000,
    http: {
      method: 'POST',
      path: '/api/validate',
      headers: [{ key: 'Content-Type', value: 'application/json' }, ...BROWSER_HEADERS],
    },
    sections: [
      { id: SECTION.target, title: 'Primary Target' },
      { id: 'sv_http', title: 'Schema Input Validation Parameters', accent: true },
      { id: 'request', title: '' },
      { id: 'sv_cases', title: '' },
      { id: 'sv_config', title: 'Validation Config' },
    ],
    fields: [
      methodField('sv_http', 'POST'),
      pathField('sv_http', '/api/validate'),
      { id: 'sv.cases_heading', type: 'section', section: 'sv_cases', label: 'Fuzzing Test Cases:' },
      linesField(
        'sv.fuzz_cases',
        'sv_cases',
        'Fuzz Cases (one per line)',
        ['{}', '{"a":1}', '{"a":"b"}'],
        'One malformed body per line — sent once per content type',
      ),
      { id: 'sv.ct_heading', type: 'section', section: 'sv_cases', label: 'Content Types to Test' },
      linesField(
        'sv.content_types',
        'sv_cases',
        'Content Types (one per line)',
        ['application/json', 'application/xml', 'text/plain', 'application/x-www-form-urlencoded'],
        'One Content-Type per line',
      ),
      {
        id: 'sv.endpoint',
        type: 'text',
        section: 'sv_config',
        label: 'Validation Endpoint',
        default: '/api/validate',
        hint: 'API endpoint that validates input schema',
        mono: true,
      },
      {
        id: 'sv.expect_reject',
        type: 'checkbox',
        section: 'sv_config',
        label: 'Flag 2xx responses as findings',
        default: true,
        hint: 'A malformed body accepted with a success status indicates missing schema validation',
      },
    ],
  },
  {
    id: 'business_logic',
    category: 'api_protection',
    label: 'Business Logic Test',
    shortLabel: 'Business Logic',
    icon: 'repeat',
    blurb: 'Replay a workflow request concurrently to expose race conditions and logic abuse.',
    feasibility: 'phone',
    feasibilityNote:
      'Race-condition timing needs tight synchronisation; the server executor provides the tighter window.',
    creditCost: 1,
    defaultDurationMs: 12000,
    http: {
      method: 'POST',
      path: '/api/workflow',
      headers: [
        { key: 'Content-Type', value: 'application/json' },
        { key: 'Authorization', value: 'Bearer {{TOKEN}}' },
        ...BROWSER_HEADERS,
      ],
      body: '{"action": "redeem", "amount": 100}',
    },
    sections: [
      { id: SECTION.target, title: 'Primary Target' },
      { id: 'bl_http', title: 'Business Logic Parameters', accent: true },
      { id: 'request', title: '' },
      { id: 'bl_attack', title: 'Business Logic Attack Parameters' },
    ],
    fields: [
      methodField('bl_http', 'POST'),
      pathField('bl_http', '/api/workflow'),
      headersField('request', [
        { key: 'Content-Type', value: 'application/json' },
        { key: 'Authorization', value: 'Bearer {{TOKEN}}' },
        ...BROWSER_HEADERS,
      ]),
      bodyField('request', '{"action": "redeem", "amount": 100}'),
      numberField('bl.replay_count', 'bl_attack', 'Replay Count', {
        min: 1,
        max: 1000,
        def: 10,
        hint: 'Number of times to repeat the request (1-1000)',
      }),
      numberField('bl.delay', 'bl_attack', 'Request Delay (ms)', {
        min: 0,
        max: 10000,
        def: 100,
        hint: 'Delay between replays to test race conditions (0-10000)',
      }),
      {
        id: 'bl.endpoint',
        type: 'text',
        section: 'bl_attack',
        label: 'Business Logic Endpoint',
        default: '/api/workflow',
        hint: 'API endpoint with business logic to abuse',
        mono: true,
      },
      {
        id: 'bl.concurrent',
        type: 'checkbox',
        section: 'bl_attack',
        label: 'Fire replays concurrently (race window)',
        default: true,
        hint: 'Sends all replays at once instead of spacing them, widening the race window',
      },
    ],
  },
];

export const apiCategory: TestCategory = {
  id: 'api_protection',
  label: 'API Protection',
  icon: 'shield-half',
  accent: '#3B7DFF',
  blurb: 'Auth, authorisation and logic abuse',
  testIds: ['brute_force', 'idor_enumeration', 'schema_validation', 'business_logic'],
};
