import type { TestCategory, TestDefinition } from '../types';
import {
  bodyField,
  BROWSER_HEADERS,
  headersField,
  INJECTION_POINT_OPTIONS,
  linesField,
  methodField,
  numberField,
  pathField,
  queryField,
  SECTION,
} from './helpers';

/** Web Protection — injection and malformed-request tests against the origin/WAF. */
export const webTests: TestDefinition[] = [
  {
    id: 'sql_injection',
    category: 'web_protection',
    label: 'SQL Injection Test',
    shortLabel: 'SQL Injection',
    icon: 'shield',
    blurb: 'Inject SQL payloads into a chosen parameter and detect database error leakage or boolean divergence.',
    feasibility: 'phone',
    feasibilityNote: 'Pure HTTP request/response work — fully effective from a handset.',
    creditCost: 1,
    defaultDurationMs: 8000,
    http: {
      method: 'POST',
      path: '/login',
      query: [
        { key: 'id', value: '{{PAYLOAD}}' },
        { key: 'action', value: 'login' },
      ],
      body: 'username={{PAYLOAD}}&password=test123',
    },
    sections: [
      { id: SECTION.target, title: 'Primary Target' },
      { id: 'sql_http', title: 'SQL Injection Parameters', accent: true },
      { id: 'request', title: '' },
      { id: 'sql_attack', title: 'SQL Injection Attack Parameters' },
    ],
    fields: [
      methodField('sql_http', 'POST'),
      pathField('sql_http', '/login'),
      queryField('request', [
        { key: 'id', value: '{{PAYLOAD}}' },
        { key: 'action', value: 'login' },
      ]),
      headersField('request', BROWSER_HEADERS),
      bodyField('request', 'username={{PAYLOAD}}&password=test123'),
      {
        id: 'sql.payloads_heading',
        type: 'section',
        section: 'sql_attack',
        label: 'SQL Injection Payloads:',
      },
      linesField(
        'sql.payloads',
        'sql_attack',
        'SQL Payloads (one per line)',
        ["1' OR 1=1--", "1' UNION SELECT", "'; DROP TABLE users--"],
        'One payload per line',
      ),
      {
        id: 'sql.injection_point',
        type: 'segmented',
        section: 'sql_attack',
        label: 'Injection Point:',
        default: 'query',
        options: INJECTION_POINT_OPTIONS,
      },
      {
        id: 'sql.target_param',
        type: 'text',
        section: 'sql_attack',
        label: 'Target Parameter',
        default: 'id',
        hint: 'Parameter name to inject SQL payloads into',
      },
      {
        id: 'sql.technique',
        type: 'select',
        section: 'sql_attack',
        label: 'Detection Technique',
        default: 'auto',
        advanced: true,
        options: [
          { label: 'Auto (error + boolean + time)', value: 'auto' },
          { label: 'Error-based', value: 'error' },
          { label: 'Boolean-based blind', value: 'boolean' },
          { label: 'Time-based blind', value: 'time' },
        ],
      },
      numberField('sql.time_delay', 'sql_attack', 'Time-based Delay (seconds)', {
        min: 1,
        max: 30,
        def: 5,
        hint: 'Sleep duration used for time-based blind detection (1-30 seconds)',
        step: 1,
      }),
    ],
  },
  {
    id: 'xss',
    category: 'web_protection',
    label: 'XSS Test',
    shortLabel: 'XSS',
    icon: 'shield',
    blurb: 'Reflect script payloads and detect unescaped output, plus WAF filter bypasses.',
    feasibility: 'phone',
    feasibilityNote:
      'Reflected-XSS detection is pure HTTP. Stored and DOM-based confirmation is delegated to the server executor, which runs a headless browser.',
    creditCost: 1,
    defaultDurationMs: 8000,
    http: {
      method: 'POST',
      path: '/comment',
      query: [
        { key: 'q', value: '{{PAYLOAD}}' },
        { key: 'page', value: '1' },
      ],
      body: 'comment={{PAYLOAD}}&submit=true',
    },
    sections: [
      { id: SECTION.target, title: 'Primary Target' },
      { id: 'xss_http', title: 'XSS Testing Parameters', accent: true },
      { id: 'request', title: '' },
      { id: 'xss_attack', title: 'Cross-Site Scripting (XSS) Attack Parameters' },
    ],
    fields: [
      methodField('xss_http', 'POST'),
      pathField('xss_http', '/comment'),
      queryField('request', [
        { key: 'q', value: '{{PAYLOAD}}' },
        { key: 'page', value: '1' },
      ]),
      headersField('request', BROWSER_HEADERS),
      bodyField('request', 'comment={{PAYLOAD}}&submit=true'),
      { id: 'xss.payloads_heading', type: 'section', section: 'xss_attack', label: 'XSS Payloads:' },
      linesField(
        'xss.payloads',
        'xss_attack',
        'XSS Payloads (one per line)',
        [
          "<script>alert('XSS')</script>",
          "<img src=x onerror=alert('XSS')>",
          "javascript:alert('XSS')",
        ],
        'One payload per line',
      ),
      {
        id: 'xss.injection_point',
        type: 'segmented',
        section: 'xss_attack',
        label: 'Injection Point:',
        default: 'query',
        options: INJECTION_POINT_OPTIONS,
      },
      {
        id: 'xss.context',
        type: 'select',
        section: 'xss_attack',
        label: 'Reflection Context',
        default: 'auto',
        advanced: true,
        options: [
          { label: 'Auto-detect', value: 'auto' },
          { label: 'HTML body', value: 'html' },
          { label: 'HTML attribute', value: 'attribute' },
          { label: 'JavaScript string', value: 'js' },
          { label: 'URL / href', value: 'url' },
        ],
      },
    ],
  },
  {
    id: 'path_traversal',
    category: 'web_protection',
    label: 'Path Traversal Test',
    shortLabel: 'Path Traversal',
    icon: 'folder-open',
    blurb: 'Probe for directory traversal to read files outside the web root.',
    feasibility: 'phone',
    feasibilityNote: 'Pure HTTP request/response work — fully effective from a handset.',
    creditCost: 1,
    defaultDurationMs: 8000,
    http: {
      method: 'GET',
      path: '/download',
      query: [{ key: 'file', value: '{{PAYLOAD}}' }],
      headers: [{ key: 'X-Forwarded-For', value: '10.0.0.1' }],
    },
    sections: [
      { id: SECTION.target, title: 'Primary Target' },
      { id: 'pt_http', title: 'Path Traversal Parameters', accent: true },
      { id: 'request', title: '' },
      { id: 'pt_attack', title: 'Path Traversal Attack Parameters' },
    ],
    fields: [
      methodField('pt_http', 'GET'),
      pathField('pt_http', '/download'),
      queryField('request', [{ key: 'file', value: '{{PAYLOAD}}' }]),
      headersField('request', [
        { key: 'X-Forwarded-For', value: '10.0.0.1' },
        ...BROWSER_HEADERS,
      ]),
      {
        id: 'pt.payloads_heading',
        type: 'section',
        section: 'pt_attack',
        label: 'Path Traversal Payloads:',
      },
      linesField(
        'pt.payloads',
        'pt_attack',
        'Path Traversal Payloads (one per line)',
        ['../../../etc/passwd', '..\\..\\..\\', '\\windows\\system32\\drivers\\etc\\hosts'],
        'One payload per line',
      ),
      {
        id: 'pt.injection_point',
        type: 'segmented',
        section: 'pt_attack',
        label: 'Injection Point:',
        default: 'query',
        options: INJECTION_POINT_OPTIONS,
      },
      {
        id: 'pt.encoding',
        type: 'select',
        section: 'pt_attack',
        label: 'Encoding',
        default: 'auto',
        advanced: true,
        options: [
          { label: 'Auto (all variants)', value: 'auto' },
          { label: 'Plain', value: 'plain' },
          { label: 'URL encoded', value: 'url' },
          { label: 'Double URL encoded', value: 'double' },
          { label: 'Unicode / overlong', value: 'unicode' },
        ],
      },
    ],
  },
  {
    id: 'oversized_body',
    category: 'web_protection',
    label: 'Oversized Body Test',
    shortLabel: 'Oversized Body',
    icon: 'document-text',
    blurb: 'Send an oversized JSON body to test request-size limits and parser hardening.',
    feasibility: 'hybrid',
    feasibilityNote:
      'Payload generation is local, but mobile uplink bandwidth makes multi-megabyte bursts slow. The server executor is used for large body sizes.',
    creditCost: 1,
    defaultDurationMs: 12000,
    http: {
      method: 'POST',
      path: '/api/upload',
      headers: [
        { key: 'Content-Type', value: 'application/json' },
        ...BROWSER_HEADERS,
      ],
    },
    sections: [
      { id: SECTION.target, title: 'Primary Target' },
      { id: 'ob_params', title: 'Oversized Body Parameters' },
      { id: 'http', title: 'HTTP Request Configuration', accent: true },
      { id: 'request', title: '' },
    ],
    fields: [
      numberField('ob.body_size_kb', 'ob_params', 'Body Size (KB)', {
        min: 1,
        max: 10240,
        def: 1024,
        hint: 'Size of request body to generate (1-10240 KB)',
      }),
      numberField('ob.json_field_count', 'ob_params', 'JSON Field Count', {
        min: 1,
        max: 1000,
        def: 1000,
        hint: 'Number of JSON fields to generate (1-1000)',
      }),
      methodField('http', 'POST'),
      pathField('http', '/api/upload'),
      headersField('request', [
        { key: 'Content-Type', value: 'application/json' },
        ...BROWSER_HEADERS,
      ]),
      {
        id: 'ob.duplicate_keys',
        type: 'checkbox',
        section: 'ob_params',
        label: 'Duplicate JSON keys',
        default: false,
        advanced: true,
      },
      {
        id: 'ob.deep_nesting',
        type: 'number',
        section: 'ob_params',
        label: 'Nesting Depth',
        min: 1,
        max: 200,
        default: 1,
        hint: 'JSON nesting depth used to stress recursive parsers (1-200)',
        advanced: true,
      },
      {
        id: 'info.ob_config',
        type: 'note',
        section: 'ob_params',
        label: 'Oversized Body Config',
        tone: 'info',
        body:
          "Configure the oversized body via the 'Request Body' section. The test engine will automatically " +
          'generate a body of the configured size, padding with JSON fields up to the configured field count.',
      },
    ],
  },
];

export const webCategory: TestCategory = {
  id: 'web_protection',
  label: 'Web Protection',
  icon: 'shield',
  accent: '#3B7DFF',
  blurb: 'WAF rules and injection defence',
  testIds: ['sql_injection', 'xss', 'path_traversal', 'oversized_body'],
};
